//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::classifications::Entity as Classifications;
pub use super::insert_stocks::Entity as InsertStocks;
pub use super::items::Entity as Items;
pub use super::notes::Entity as Notes;
pub use super::roles::Entity as Roles;
pub use super::users::Entity as Users;
